package talium.twitchCommands.controller;

import talium.twitch4J.TwitchUserPermission;
import talium.stringTemplates.TemplateDTO;
import talium.twitchCommands.cooldown.ChatCooldown;

public record TriggerDTO(
        String id,
        String description,
        MessagePatternDTO[] patterns,
        TwitchUserPermission permission,
        ChatCooldown userCooldown,
        ChatCooldown globalCooldown,
        boolean isAutoGenerated,
        TemplateDTO template
) {}

