package talium.system.twitchCommands.controller;

import talium.Twitch4J.TwitchUserPermission;
import talium.system.stringTemplates.TemplateDTO;
import talium.system.twitchCommands.cooldown.ChatCooldown;

public record TriggerDTO(
        String id,
        String description,
        MessagePatternDTO[] patterns,
        TwitchUserPermission permission,
        ChatCooldown userCooldown,
        ChatCooldown globalCooldown,
        boolean isAutoGenerated,
        TemplateDTO template
) {}

